### ISSUE TITLE
Hi! About city_drivers I have some questions!

### ISSUE THREAD

**Issue by MercyM** [reubenjohn/multiagent_envs#1]
Hi,
I see that the other two environments have observation values and action values based on reinforcement learning, but city_drivers environment does not seem to have. How should I train?

Looking forward to your reply. Thanks!
                                                                                              Sincerely, Peng.

**Comment by reubenjohn** [comment]
Hey Peng, I somehow missed your message! This project has not been maintained in a while. The city_driver environment was not completed and the current implementation has the agents accessing the internal details of the environment (kind of like an oracle), and is thus not very suitable for reinforcement learning. Sorry I could not be of much help right now, but I'd be happy to merge any PRs or answer any questions if you are interested in the project.

**Comment by MercyM** [comment]
Hi,&nbsp;
Thank you very much for your reply. I have no other questions.
Peng.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Reuben ***@***.***&gt;; 
发送时间: 2021年12月14日(星期二) 下午3:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reubenjohn/multiagent_envs] Hi! About city_drivers I have some questions! (Issue #1)





 
嘿彭，我不知怎么错过了你的消息！这个项目已经有一段时间没有维护了。city_driver 环境没有完成，当前的实现有代理访问环境的内部细节（有点像 oracle），因此不太适合强化学习。抱歉，我现在帮不上什么忙，但如果您对该项目感兴趣，我很乐意合并任何 PR 或回答任何问题。
 
—
您收到此消息是因为您创作了该线程。
直接回复本邮件，在 GitHub 上查看，或退订。
使用 GitHub Mobile for iOS或Android随时随地分类通知。
